
import type { Event, Resource, Capsule, Project, GalleryImage } from "./types";

export const mockEvents: Event[] = [
  {
    id: "1",
    title: "GDG Cloud Community Day",
    description:
      "Join us for a full day of learning about Google Cloud technologies with hands-on workshops and expert sessions.",
    date: "2024-09-15",
    location: "Online",
    organizer: "GDG Cloud City",
    type: "GDG Event",
    imageUrl: "https://placehold.co/600x400.png",
    imageHint: "cloud technology",
    tags: ["Google Cloud", "DevOps", "AI/ML"],
  },
  {
    id: "2",
    title: "Flutter Forward Extended",
    description:
      "Catch up on the latest updates from the Flutter team. We will have live coding sessions and a Q&A panel.",
    date: "2024-10-02",
    location: "Virtual Event",
    organizer: "Flutter Devs Pune",
    type: "GDG Event",
    imageUrl: "https://placehold.co/600x400.png",
    imageHint: "mobile development",
    tags: ["Flutter", "Mobile", "Dart"],
  },
  {
    id: "3",
    title: "Android Dev Summit Recap",
    description:
      "A deep dive into the most important announcements from the Android Dev Summit. Demos and discussions included.",
    date: "2024-11-10",
    location: "Community Hall",
    organizer: "Android Gurus",
    type: "GDG Event",
    imageUrl: "https://placehold.co/600x400.png",
    imageHint: "android phone",
    tags: ["Android", "Kotlin", "Jetpack Compose"],
  },
  {
    id: "4",
    title: "Intro to Web Accessibility",
    description:
      "A practical session on making your web applications accessible to everyone. Learn about ARIA, screen readers, and more.",
    date: "2024-09-20",
    location: "Online Workshop",
    organizer: "Web Weavers",
    type: "Tech Session",
    imageUrl: "https://placehold.co/600x400.png",
    imageHint: "web accessibility",
    tags: ["Web Dev", "A11y", "React"],
  },
  {
    id: "5",
    title: "Firebase for Startups",
    description:
      "Discover how to leverage Firebase to build and scale your startup faster. Covers Auth, Firestore, and Cloud Functions.",
    date: "2024-10-18",
    location: "Startup Hub",
    organizer: "Firebase Fanatics",
    type: "Tech Session",
    imageUrl: "https://placehold.co/600x400.png",
    imageHint: "firebase startup",
    tags: ["Firebase", "Startups", "Backend"],
  },
  {
    id: "6",
    title: "Modern CSS Deep Dive",
    description:
      "Explore the latest features in CSS, including container queries, cascade layers, and new color spaces.",
    date: "2024-11-05",
    location: "Online",
    organizer: "CSS Masters",
    type: "Tech Session",
    imageUrl: "https://placehold.co/600x400.png",
    imageHint: "css code",
    tags: ["CSS", "Web Design", "Frontend"],
  },
];

export const mockTeam = [
  {
    id: "1",
    name: "Ojas Bhalerao",
    role: "GDG Lead 24-25",
    imageUrl: "https://placehold.co/400x400.png",
    imageHint: "person portrait",
    linkedinUrl: "https://www.linkedin.com/in/ojas-bhalerao-9742282b3/",
  },
];

export const mockGalleryImages: GalleryImage[] = [
  { id: '1', src: 'https://placehold.co/400x400.png', alt: 'Team working on a project', hint: 'team collaboration', caption: 'Hackathon Brainstorming' },
  { id: '2', src: 'https://placehold.co/400x400.png', alt: 'Group photo at a tech talk', hint: 'group photo', caption: 'Post-Event Group Photo' },
  { id: '3', src: 'https://placehold.co/400x400.png', alt: 'Presenter at a workshop', hint: 'public speaking', caption: 'Live Coding Workshop' },
  { id: '4', src: 'https://placehold.co/400x400.png', alt: 'Team members networking', hint: 'people talking', caption: 'Networking at Annual Meetup' },
  { id: '5', src: 'https://placehold.co/400x400.png', alt: 'Celebrating a project launch', hint: 'team celebration', caption: 'Project Launch Celebration' },
  { id: '6', src: 'https://placehold.co/400x400.png', alt: 'Casual team lunch', hint: 'team lunch', caption: 'Team Lunch' },
];

export const mockCapsules: Capsule[] = [
    { id: '1', title: 'Git Stash', tip: 'Use `git stash -u` to include untracked files.', category: 'Git', emoji: '🗂️' },
    { id: '2', title: 'CSS Flexbox', tip: '`justify-content` aligns on main axis, `align-items` on cross axis.', category: 'Web', emoji: '↔️' },
    { id: '3', title: 'React Keys', tip: 'Keys help React identify which items have changed, are added, or are removed.', category: 'Web', emoji: '🔑' },
    { id: '4', title: 'JS Destructuring', tip: 'Easily extract array values or object properties into distinct variables.', category: 'Web', emoji: '💡' },
    { id: '5', title: 'TypeScript Enums', tip: 'Use enums for a set of named constants, like `enum Color {Red, Green}`.', category: 'Web', emoji: '🏷️' },
    { id: '6', title: 'Next.js Image', tip: 'The `<Image>` component automatically optimizes images for performance.', category: 'Web', emoji: '🖼️' },
    { id: '7', title: 'VS Code Shortcut', tip: '`Ctrl+D` selects next occurrence of the current word.', category: 'Tools', emoji: '⌨️' },
    { id: '8', title: 'Firebase Rules', tip: 'Always secure your Firestore database with proper security rules.', category: 'Web', emoji: '🔒' },
    { id: '9', title: 'Gemini System Prompt', tip: 'Use a `system` instruction to guide the model\'s behavior and personality.', category: 'AI', emoji: '🤖' },
    { id: '10', title: 'Flutter Widgets', tip: 'In Flutter, almost everything is a widget, from a button to padding.', category: 'Mobile', emoji: '📱' },
    { id: '11', title: 'Android Vector Drawables', tip: 'Use Vector Drawables for sharp, scalable icons that reduce APK size.', category: 'Mobile', emoji: '✏️' },
];

export const googleTools: Resource[] = [
  {
    id: 'g-1',
    name: 'Firebase',
    category: 'Google & Firebase',
    description: 'An app development platform for building and growing apps, backed by Google.',
    logoUrl: 'https://www.gstatic.com/devrel-devsite/prod/v874c5d871cf34262c5b3d9d683664d471a41493a3841e2f893a3b54435b87c71/firebase/images/lockup.svg',
    toolLink: 'https://firebase.google.com/',
    learnLink: 'https://firebase.google.com/docs',
  },
  {
    id: 'g-2',
    name: 'Gemini',
    category: 'Google & Firebase',
    description: 'A family of generative AI models from Google AI for multimodal reasoning.',
    logoUrl: 'https://www.gstatic.com/lamda/images/gemini_lockup_gm_horizontal_20231206_blue_158x26_v2_hr.svg',
    toolLink: 'https://ai.google.dev/',
    learnLink: 'https://ai.google.dev/docs',
  },
  {
    id: 'g-3',
    name: 'Google Colab',
    category: 'Google & Firebase',
    description: 'Execute Python in your browser with zero configuration and free access to GPUs.',
    logoUrl: 'https://colab.research.google.com/img/colab_favicon_256px.png',
    toolLink: 'https://colab.research.google.com/',
    learnLink: 'https://colab.research.google.com/',
  },
  {
    id: 'g-4',
    name: 'Flutter',
    category: 'Google & Firebase',
    description: 'Google\'s UI toolkit for building beautiful, natively compiled cross-platform applications.',
    logoUrl: 'https://storage.googleapis.com/cms-storage-bucket/4fd5520fe28eb2a65a44.svg',
    toolLink: 'https://flutter.dev/',
    learnLink: 'https://flutter.dev/docs',
  },
  {
    id: 'g-5',
    name: 'Android Studio',
    category: 'Google & Firebase',
    description: 'The official IDE for Android app development, built on JetBrains\' IntelliJ IDEA software.',
    logoUrl: 'https://developer.android.com/static/studio/images/new-studio-logo-1-1.svg',
    toolLink: 'https://developer.android.com/studio',
    learnLink: 'https://developer.android.com/docs',
  },
  {
    id: 'g-6',
    name: 'Google Cloud',
    category: 'Google & Firebase',
    description: 'A suite of cloud computing services that runs on the same infrastructure as Google.',
    logoUrl: 'https://cloud.google.com/images/social-icon-google-cloud-1200-v2.png',
    toolLink: 'https://cloud.google.com/',
    learnLink: 'https://cloud.google.com/docs',
  },
  {
    id: 'g-7',
    name: 'TensorFlow',
    category: 'Google & Firebase',
    description: 'An end-to-end open source platform for machine learning.',
    logoUrl: 'https://www.tensorflow.org/static/images/favicon.png',
    toolLink: 'https://www.tensorflow.org/',
    learnLink: 'https://www.tensorflow.org/tutorials',
  },
  {
    id: 'g-8',
    name: 'Kaggle',
    category: 'Google & Firebase',
    description: 'An online community of data scientists and machine learning practitioners.',
    logoUrl: 'https://www.kaggle.com/static/images/favicon.ico',
    toolLink: 'https://www.kaggle.com/',
    learnLink: 'https://www.kaggle.com/learn',
  },
  {
    id: 'g-9',
    name: 'Google Analytics',
    category: 'Google & Firebase',
    description: 'A web analytics service that tracks and reports website traffic.',
    logoUrl: 'https://www.google.com/analytics/static/images/favicon.ico',
    toolLink: 'https://analytics.google.com/',
    learnLink: 'https://support.google.com/analytics/?hl=en#topic=14093815',
  },
  {
    id: 'g-10',
    name: 'Chrome DevTools',
    category: 'Google & Firebase',
    description: 'A set of web developer tools built directly into the Google Chrome browser.',
    logoUrl: 'https://developer.chrome.com/images/favicon.png',
    toolLink: 'https://developer.chrome.com/docs/devtools',
    learnLink: 'https://developer.chrome.com/docs/devtools/overview',
  },
  {
    id: 'g-11',
    name: 'Lighthouse',
    category: 'Google & Firebase',
    description: 'An open-source, automated tool for improving the quality of web pages.',
    logoUrl: 'https://developer.chrome.com/static/images/lighthouse-logo.svg',
    toolLink: 'https://developer.chrome.com/docs/lighthouse/overview/',
    learnLink: 'https://web.dev/learn/performance/',
  },
   {
    id: 'g-12',
    name: 'Material Design',
    category: 'Google & Firebase',
    description: 'A design system created by Google to help teams build high-quality digital experiences.',
    logoUrl: 'https://material.io/static/images/favicon.ico',
    toolLink: 'https://material.io/',
    learnLink: 'https://m3.material.io/',
  },
];

export const aiTools: Resource[] = [
  {
    id: 'ai-1',
    name: 'ChatGPT',
    category: 'AI',
    description: 'A conversational AI model by OpenAI, capable of understanding and generating human-like text.',
    logoUrl: 'https://openai.com/favicon.ico',
    toolLink: 'https://chat.openai.com/',
    learnLink: 'https://platform.openai.com/docs',
  },
  {
    id: 'ai-2',
    name: 'Claude AI',
    category: 'AI',
    description: 'A family of large language models developed by Anthropic, focused on safety and helpfulness.',
    logoUrl: 'https://www.anthropic.com/images/icons/apple-touch-icon.png',
    toolLink: 'https://claude.ai/',
    learnLink: 'https://docs.anthropic.com/claude/reference/getting-started-with-the-api',
  },
  {
    id: 'ai-3',
    name: 'Perplexity AI',
    category: 'AI',
    description: 'An AI-powered search engine and conversational assistant that provides direct answers with citations.',
    logoUrl: 'https://www.perplexity.ai/favicon.svg',
    toolLink: 'https://www.perplexity.ai/',
    learnLink: 'https://docs.perplexity.ai/',
  },
  {
    id: 'ai-4',
    name: 'Poe by Quora',
    category: 'AI',
    description: 'A platform to ask questions, get instant answers, and have back-and-forth conversations with AI bots.',
    logoUrl: 'https://poe.com/favicon.ico',
    toolLink: 'https://poe.com/',
    learnLink: 'https://developer.poe.com/server-bots/official-bots-and-pricing',
  },
  {
    id: 'ai-5',
    name: 'Vercel v0',
    category: 'AI',
    description: 'A generative UI system by Vercel that creates custom components on the fly from text prompts.',
    logoUrl: 'https://assets.vercel.com/image/upload/front/favicon/vercel/favicon.ico',
    toolLink: 'https://v0.dev/',
    learnLink: 'https://v0.dev/faq',
  },
   {
    id: 'ai-6',
    name: 'Phind',
    category: 'AI',
    description: 'An AI search engine and pair programmer for developers, providing code examples and technical answers.',
    logoUrl: 'https://phind.com/favicon.ico',
    toolLink: 'https://phind.com/',
    learnLink: 'https://phind.com/api',
  },
  {
    id: 'ai-7',
    name: 'Hugging Face',
    category: 'AI',
    description: 'A community and data science platform that provides tools for building, training and deploying ML models.',
    logoUrl: 'https://huggingface.co/favicon.ico',
    toolLink: 'https://huggingface.co/',
    learnLink: 'https://huggingface.co/docs',
  },
  {
    id: 'ai-8',
    name: 'Midjourney',
    category: 'AI',
    description: 'An independent research lab that produces a proprietary artificial intelligence program that creates images from textual descriptions.',
    logoUrl: 'https://media.discordapp.net/attachments/1041133746691604530/1121048639825944646/midjourney_icon.png',
    toolLink: 'https://www.midjourney.com/',
    learnLink: 'https://docs.midjourney.com/',
  },
  {
    id: 'ai-9',
    name: 'Replicate',
    category: 'AI',
    description: 'Run open-source machine learning models with a cloud API.',
    logoUrl: 'https://replicate.com/favicon.ico',
    toolLink: 'https://replicate.com/',
    learnLink: 'https://replicate.com/docs',
  },
  {
    id: 'ai-10',
    name: 'LangChain',
    category: 'AI',
    description: 'A framework for developing applications powered by language models.',
    logoUrl: 'https://www.langchain.com/favicon.ico',
    toolLink: 'https://www.langchain.com/',
    learnLink: 'https://python.langchain.com/v0.2/docs/introduction/',
  },
   {
    id: 'ai-11',
    name: 'Runway',
    category: 'AI',
    description: 'An applied AI research company shaping the next era of art, entertainment and human creativity.',
    logoUrl: 'https://runwayml.com/favicon.ico',
    toolLink: 'https://runwayml.com/',
    learnLink: 'https://learn.runwayml.com/',
  },
];

export const devTools: Resource[] = [
  {
    id: 'dev-1',
    name: 'Next.js',
    category: 'Developer',
    description: 'The React framework for building full-stack web applications with server-side rendering and static site generation.',
    logoUrl: 'https://nextjs.org/favicon.ico',
    toolLink: 'https://nextjs.org/',
    learnLink: 'https://nextjs.org/docs',
  },
  {
    id: 'dev-2',
    name: 'Figma',
    category: 'Developer',
    description: 'A collaborative interface design tool that allows teams to design, prototype, and gather feedback all in one place.',
    logoUrl: 'https://static.figma.com/app/icon/1/favicon.png',
    toolLink: 'https://www.figma.com/',
    learnLink: 'https://help.figma.com/hc/en-us',
  },
  {
    id: 'dev-3',
    name: 'Tailwind CSS',
    category: 'Developer',
    description: 'A utility-first CSS framework for rapidly building custom user interfaces without leaving your HTML.',
    logoUrl: 'https://tailwindcss.com/favicons/favicon.ico?v=3',
    toolLink: 'https://tailwindcss.com/',
    learnLink: 'https://tailwindcss.com/docs/installation',
  },
  {
    id: 'dev-4',
    name: 'GitHub',
    category: 'Developer',
    description: 'A web-based platform for version control using Git, plus project management and collaboration features.',
    logoUrl: 'https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png',
    toolLink: 'https://github.com/',
    learnLink: 'https://docs.github.com/en',
  },
  {
    id: 'dev-5',
    name: 'VS Code',
    category: 'Developer',
    description: 'A free, lightweight, and powerful source-code editor that runs on your desktop and is available for all platforms.',
    logoUrl: 'https://code.visualstudio.com/favicon.ico',
    toolLink: 'https://code.visualstudio.com/',
    learnLink: 'https://code.visualstudio.com/docs',
  },
   {
    id: 'dev-6',
    name: 'Supabase',
    category: 'Developer',
    description: 'An open-source Firebase alternative providing a Postgres database, authentication, storage, and auto-generated APIs.',
    logoUrl: 'https://supabase.com/favicon/favicon.ico',
    toolLink: 'https://supabase.com/',
    learnLink: 'https://supabase.com/docs',
  },
  {
    id: 'dev-7',
    name: 'Docker',
    category: 'Developer',
    description: 'A platform for developing, shipping, and running applications in containers.',
    logoUrl: 'https://www.docker.com/favicon.ico',
    toolLink: 'https://www.docker.com/',
    learnLink: 'https://docs.docker.com/',
  },
  {
    id: 'dev-8',
    name: 'Postman',
    category: 'Developer',
    description: 'An API platform for developers to design, build, test and iterate their APIs.',
    logoUrl: 'https://www.postman.com/favicon.ico',
    toolLink: 'https://www.postman.com/',
    learnLink: 'https://learning.postman.com/',
  },
  {
    id: 'dev-9',
    name: 'Notion',
    category: 'Developer',
    description: 'The connected workspace where better, faster work happens.',
    logoUrl: 'https://www.notion.so/images/favicon.ico',
    toolLink: 'https://www.notion.so/',
    learnLink: 'https://www.notion.so/help',
  },
  {
    id: 'dev-10',
    name: 'shadcn/ui',
    category: 'Developer',
    description: 'Beautifully designed components that you can copy and paste into your apps.',
    logoUrl: 'https://ui.shadcn.com/favicon.ico',
    toolLink: 'https://ui.shadcn.com/',
    learnLink: 'https://ui.shadcn.com/docs',
  },
  {
    id: 'dev-11',
    name: 'Storybook',
    category: 'Developer',
    description: 'A frontend workshop for building UI components and pages in isolation.',
    logoUrl: 'https://storybook.js.org/favicon.ico',
    toolLink: 'https://storybook.js.org/',
    learnLink: 'https://storybook.js.org/docs/',
  },
   {
    id: 'dev-12',
    name: 'Sentry',
    category: 'Developer',
    description: 'Application monitoring and error tracking software.',
    logoUrl: 'https://sentry.io/favicon.ico',
    toolLink: 'https://sentry.io/',
    learnLink: 'https://docs.sentry.io/',
  },
];


export const mockProjects: Project[] = [
  {
    id: "1",
    title: "Community Event Platform",
    description: "A full-stack web app for managing GDG events, registrations, and feedback, built with Next.js and Firebase.",
    category: "Web",
    tags: ["Next.js", "Firebase", "Tailwind CSS", "Genkit"],
    contributors: [
      { name: "Alice", role: "Frontend Dev" },
      { name: "Bob", role: "Backend Dev" },
    ],
    link: "https://github.com/",
    imageUrl: "https://placehold.co/600x400.png",
    imageHint: "web application screenshot"
  },
  {
    id: "2",
    title: "Campus Companion App",
    description: "A cross-platform mobile app to help students navigate campus, find study spots, and connect with peers.",
    category: "Mobile",
    tags: ["Flutter", "Dart", "Firebase Auth"],
    contributors: [
      { name: "Charlie", role: "Flutter Dev" },
      { name: "Diana", role: "UI/UX Designer" },
    ],
    link: "https://github.com/",
    imageUrl: "https://placehold.co/600x400.png",
    imageHint: "mobile app screen"
  },
  {
    id: "3",
    title: "AI-Powered News Summarizer",
    description: "An AI tool that fetches the latest tech news and provides concise, easy-to-read summaries using Gemini.",
    category: "AI",
    tags: ["Python", "Gemini", "Flask", "Genkit"],
    contributors: [
      { name: "Eve", role: "AI Engineer" },
      { name: "Frank", role: "API Developer" },
    ],
    link: "https://github.com/",
    imageUrl: "https://placehold.co/600x400.png",
    imageHint: "artificial intelligence abstract"
  },
  {
    id: "4",
    title: "Cloud Function Automation",
    description: "A set of serverless functions to automate community management tasks like sending reminders and updating leaderboards.",
    category: "Web",
    tags: ["Google Cloud", "Node.js", "Firestore"],
    contributors: [
      { name: "Grace", role: "Cloud Engineer" },
    ],
    link: "https://github.com/",
    imageUrl: "https://placehold.co/600x400.png",
    imageHint: "cloud infrastructure diagram"
  }
];
