
import type {NextConfig} from 'next';

const nextConfig: NextConfig = {
  /* config options here */
  typescript: {
    ignoreBuildErrors: true,
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: 'placehold.co' },
      { protocol: 'https', hostname: 'www.gstatic.com' },
      { protocol: 'https', hostname: 'res.cloudinary.com' },
      { protocol: 'https', hostname: 'colab.research.google.com' },
      { protocol: 'https', hostname: 'storage.googleapis.com' },
      { protocol: 'https', hostname: 'developer.android.com' },
      { protocol: 'https', hostname: 'cloud.google.com' },
      { protocol: 'https', hostname: 'openai.com' },
      { protocol: 'https', hostname: 'www.anthropic.com' },
      { protocol: 'https', hostname: 'www.perplexity.ai' },
      { protocol: 'https', hostname: 'poe.com' },
      { protocol: 'https', hostname: 'assets.vercel.com' },
      { protocol: 'https', hostname: 'phind.com' },
      { protocol: 'https', hostname: 'nextjs.org' },
      { protocol: 'https', hostname: 'static.figma.com' },
      { protocol: 'https', hostname: 'tailwindcss.com' },
      { protocol: 'https', hostname: 'github.githubassets.com' },
      { protocol: 'https', hostname: 'code.visualstudio.com' },
      { protocol: 'https', hostname: 'supabase.com' },
      { protocol: 'https', hostname: 'www.tensorflow.org' },
      { protocol: 'https', hostname: 'www.kaggle.com' },
      { protocol: 'https', hostname: 'www.google.com' },
      { protocol: 'https', hostname: 'developer.chrome.com' },
      { protocol: 'https', hostname: 'material.io' },
      { protocol: 'https', hostname: 'huggingface.co' },
      { protocol: 'https', hostname: 'media.discordapp.net' },
      { protocol: 'https', hostname: 'replicate.com' },
      { protocol: 'https', hostname: 'www.langchain.com' },
      { protocol: 'https', hostname: 'runwayml.com' },
      { protocol: 'https', hostname: 'www.docker.com' },
      { protocol: 'https', hostname: 'www.postman.com' },
      { protocol: 'https', hostname: 'www.notion.so' },
      { protocol: 'https', hostname: 'ui.shadcn.com' },
      { protocol: 'https', hostname: 'storybook.js.org' },
      { protocol: 'https', hostname: 'sentry.io' },
      { protocol: 'https', hostname: 'keras.io' },
      { protocol: 'https', hostname: 'angular.dev' },
      { protocol: 'https', hostname: 'fonts.google.com' },
      { protocol: 'https', hostname: 'g.co' },
      { protocol: 'https', hostname: 'dart.dev' },
      { protocol: 'https', hostname: 'ai.meta.com' },
      { protocol: 'https', hostname: 'leonardo.ai' },
      { protocol: 'https', hostname: 'mistral.ai' },
      { protocol: 'https', hostname: 'x.ai' },
      { protocol: 'https', hostname: 'suno.com' },
      { protocol: 'https', hostname: 'replit.com' },
      { protocol: 'https', hostname: 'cpwebassets.codepen.io' },
      { protocol: 'https', hostname: 'astro.build' },
      { protocol: 'https', hostname: 'svelte.dev' },
      { protocol: 'https', hostname: 'stackblitz.com' },
      { protocol: 'https', hostname: 'grafana.com' },
    ],
  },
};

export default nextConfig;
